BookAjaxApp/urls.py
from django.conf.urls import url
from django.contrib import admin
from bookajax import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.book_list, name='book_list'),
    url(r'^crud/(?P<status>[^/]+)/$', views.crud, name='crud'),
]

bookajax/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)


    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse('book_list', kwargs={'pk': self.pk})

bookajax/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('title', 'publication_date', 'author', 'price', 'pages', 'book_type')

bookajax/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string
from .models import Book
from .forms import BookForm


# Create your views here.


def book_list(request):
    template_name = 'bookajax/index.html'
    return render(request, template_name, locals())


def crud(request, status):
    context = {}
    if request.method == 'GET':
        if status == 'get_book_list':
            books = Book.objects.all()
            context['template'] = render_to_string('bookajax/book_list.html', {'books': books})
            return JsonResponse(context, status=200, safe=False)
        elif status == 'get_book_form':
            form = BookForm()
            context['template'] = render_to_string('bookajax/book_create.html', {'form': form})
            return JsonResponse(context, status=200, safe=False)
        elif status == 'get_book_edit_form':
            form = BookForm(instance=Book.objects.get(pk=request.GET.get('pk')))
            context['template'] = render_to_string('bookajax/book_create.html', {'form': form})
            return JsonResponse(context, status=200, safe=False)
    else:
        if status == 'save':
            form = BookForm(request.POST or None)
            if form.is_valid():
                form.save()
                context['status'] = 'success'
                context['message'] = 'Book successfully created'
            else:
                print(form.errors)
                context['status'] = 'error'
                context['message'] = 'Something went wrong while creating this book'
            return JsonResponse(context, status=200, safe=False)


# not using this one
def book_ajax_create_demo(request):
    # data = dict()
    template_name = 'bookajax/book_create.html'
    if request.method == 'POST':
        form = BookForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, f'Book is Created')
            return redirect('book_list')
    else:
        form = BookForm()
    context = {'form': form}
    return render(request, template_name, context)


def book_ajax_create(request):
    data = dict()
    template_name = 'bookajax/book_create.html'
    if request.method == 'GET':
        form = BookForm()
        context = {'form': form}
        return render(request, template_name, context)
        # data['html_form'] = render_to_string(template_name, context, request=request)
        # return JsonResponse(data)
    elif request.method == 'POST':
        form = BookForm(request.POST or None)
        if form.is_valid():
            form.save()
            data['html_form_status'] = True
            books = Book.objects.all()
            context = {'books': books}
            data['html_form_mssg'] = messages.warning(request, f'Book is created')
            data['html_form_data'] = render_to_string('bookajax/book_list.html', context)
        else:
            data['html_form_status'] = False
        context = {'form': form}
        data['html_form'] = render_to_string(template_name, context)
        return JsonResponse(data, status=200, safe=False)


# Edit and delete functions not converted to ajax yet ..

def book_ajax_update(request, pk):
    template_name = 'bookajax/book_update.html'
    book = get_object_or_404(Book, id=pk)
    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            messages.success(request, f' Book is updated ')
            return redirect('book_list')
    else:
        form = BookForm(instance=book)
    context = {"form": form}
    return render(request, template_name, context)


def book_ajax_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    book.delete()
    messages.warning(request, f'Book {book.title} is deleted')
    return redirect('book_list')

bookajax/templates/bookajax/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bookstore - Ajax book store implementation </title>
    <link rel="stylesheet" type="text/css" href="{% static 'bookajax/css/bootstrap.min.css' %}">
    <link href="{% static 'bookajax/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}" rel="stylesheet">

</head>
<body id="root_attach">
{% csrf_token %}
<!---the navigation will be here -->
<nav class="navbar navbar-expand-md bg-dark navbar-dark pt-2 fixed-top">
    <div class="container">
        <a class="navbar-brand btn btn-info" onclick="getBook('/crud/get_book_list')">BookStore</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ">
                <li><a class="btn btn-info" onclick="getBook('/crud/get_book_form')">Add Book</a></li>
            </ul>
        </div>
    </div>
</nav>

<!---the end of the navigation -->
<div class="container mt-3 pt-5">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
</div>
<div class="container">
    {% block content %}
        <!--content placement-->
    {% endblock %}
</div>

<script src="{% static 'bookajax/js/jquery.min.js' %}"></script>
<script src="{% static 'bookajax/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'bookajax/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'bookajax/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bookajax/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'bookajax/js/custom.js' %}"></script>

<script>
    {#        $(function () {#}
    {#           $("#js_add").click(function () {#}
    {#               // its not even getting to this line at all...#}
    {#               $("#js_book_create").submit(function (event) {#}
    {#                   event.preventDefault();#}
    {#                   console.log("We are inside the function");#}
    {#                  var form = $(this);#}
    {#                  $.ajax({#}
    {#                      url: form.attr("action"),#}
    {#                      data: form.serialize(),#}
    {#                      type: form.attr("method"),#}
    {#                      dataType: 'json',#}
    {#                      beforeSend: function (data) {#}
    {#                        $(".js_form_body").html(data.html_form);#}
    {#                      },#}
    {#                      success: function (data) {#}
    {#                          if(data.html_form_status){#}
    {#                              $("#book-table tbody").html(data.html_form_success);#}
    {#                          }#}
    {#                          else{#}
    {#                              $("#js_form_body").html(data.html_form);#}
    {#                          }#}
    {#                      }#}
    {#                  });#}
    {#                  $("#js_book_create").trigger("reset");#}
    {#                  return false;#}
    {#               });#}
    {#           });#}
    {#        });#}

    {#        $(function () {#}
    {#            $("#js_book_create").submit(function (event) {#}
    {#                   event.preventDefault();#}
    {#                   var formvalues = $(this).serialize();#}
    {#                   $.post("{% url 'book_create' %}", formvalues, function(data){#}
    {#                       if(data.html_form_status){#}
    {#                          $("#book-table tbody").html(data.html_form_success);#}
    {#                       }#}
    {#                       else{#}
    {#                           $("#js_book_create").trigger("reset");#}
    {#                       }#}
    {#                   });#}
    {#            });#}
    {#        });#}
    $(function () {
        $(".js_but").click(function () {
            alert("This page is working with Jquery");
        });

    });

</script>
</body>
</html>


{#               $.get("{% url 'book_create' %}")#}
{#                   .done(function () {#}
{#                       alert("$.get succeeded");#}
{#                   })#}
{#                   .fail(function () {#}
{#                      alert("$.get failed");#}
{#                   });#}

bookajax/templates/bookajax/book_create.html
{% load widget_tweaks %}
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            <div class="card mt-3">
                <div class="card-body">
                    <form  id="js_book_create">

                    <!---form goes in here--using django-widget_tweaks to render the form -->
                      <div class="text-center">
                          <h3 class="text-uppercase">book creation</h3><hr>
                      </div>
                      {% for field in form %}
                          <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field|add_class:'form-control' }}
                            {% for error in field.errors %}
                              <span class="help-block" style="color: darkred">{{ error }}</span>
                            {% endfor %}
                          </div>
                        {% endfor %}
                        <div class="form-group">
                          <button type="submit" class="btn btn-success">Submit</button>

                        </div>
                 </form>
                </div>
            </div>
        </div>
    </div>

bookajax/templates/bookajax/book_list.html
<div class="js_form_body">
    <table class="table" id="js_book_table">
        <thead>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Author</th>
            <th>Type</th>
            <th>Publication date</th>
            <th>Pages</th>
            <th>Price</th>
            <th>Actionz</th>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.get_book_type_display }}</td>
                <td>{{ book.publication_date }}</td>
                <td>{{ book.pages }}</td>
                <td>{{ book.price }}</td>
                <!--Needs to add js--script to the links--->
                <td style="width: 150px">
                    <a href=""
                       class="btn btn-warning btn-sm js_book_update" onclick="getId('EDIT ME '+ {{ book.id }})">Edit</a>
                    <a href=""
                       class="btn btn-Danger btn-sm js_book_delete" onclick="getId('DELETE ME '+ {{ book.id }})">Delete</a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="7" class="text-center bg-warning">No book</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

bookajax/templates/bookajax/book_update.html
{% load widget_tweaks %}
<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <div class="card mt-3 ">
            <div class="card-body">
                <form method="POST" id="js_book_update">
                    {% csrf_token %}
                    <!---form goes in here--using django-widget_tweaks to render the form -->
                    <div class="text-center">
                        <h3 class="text-uppercase">book creation</h3>
                        <hr>
                    </div>
                    {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field|add_class:'form-control' }}
                            {% for error in field.errors %}
                                <span class="help-block" style="color: darkred">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Update</button>
                        <a href="{% url 'book_list' %}" class="btn btn-danger">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

bookajax/templates/bookajax/index.html
{% extends 'bookajax/base.html' %}
{% block content %}
    <h1 class="text-black pt-3">Books List Indexing</h1>


    <div class="app-book-holder">

    </div>

{% endblock %}